Ipepe:
  Enabled: true
  DocumentationBaseURL: "https://github.com/ipepe-oss/rubocop-ipepe"

Ipepe/TernaryOperator:
  Enabled: true
  Description: "Prefer explicit if over ternary operator"
  VersionAdded: '0.1.0'

Ipepe/MultipleConditionUnless:
  Description: "`unless` with multiple conditions is not allowed"
  Enabled: true
  VersionAdded: '0.1.0'
# TODO: implement
#  EnforcedStyle: 'allow_single_condition'
#  SupportedStyles:
#    - 'allow_single_condition'
#    - 'never_unless'

Ipepe/AlphabeticalArrayOfStrings:
  Description: 'Ensure that strings in array are in alphabetical order'
  Enabled: true
  VersionAdded: '0.2.0'

Ipepe/AlphabeticalHashKeys:
  Description: 'Ensure that hash keys are in alphabetical order'
  Enabled: true
  VersionAdded: '0.2.0'
# TODO: implement
#  EnforcedStyle: 'symbols_only'
#  SupportedStyles:
#    - 'symbols_only'
#    - 'strings_only'
#    - 'symbols_and_strings'

Ipepe/RspecChangeFromToNotBy:
  Description: 'Prefer `change { }.from().to()` over `change { }.by()`'
  Enabled: true
  VersionAdded: '0.3.0'

